export const jobPosition = [
  // Executive Positions
  { value: "ceo", label: "CEO" },
  { value: "cfo", label: "CFO" },
  { value: "cmo", label: "CMO" },
  { value: "cto", label: "CTO" },
  { value: "coo", label: "COO" },

  // Tech and Engineering
  { value: "software_engineer", label: "Software Engineer" },
  { value: "frontend_developer", label: "Frontend Developer" },
  { value: "backend_developer", label: "Backend Developer" },
  { value: "fullstack_developer", label: "Fullstack Developer" },
  { value: "data_scientist", label: "Data Scientist" },
  { value: "qa_engineer", label: "QA Engineer" },
  { value: "devops_engineer", label: "DevOps Engineer" },
  { value: "ui_ux_designer", label: "UI/UX Designer" },
  { value: "graphic_designer", label: "Graphic Designer" },

  // Business and Management
  { value: "product_manager", label: "Product Manager" },
  { value: "project_manager", label: "Project Manager" },
  { value: "business_analyst", label: "Business Analyst" },
  { value: "operations_manager", label: "Operations Manager" },
  { value: "marketing_manager", label: "Marketing Manager" },
  { value: "sales_executive", label: "Sales Executive" },
  { value: "hr_manager", label: "HR Manager" },
  { value: "account_manager", label: "Account Manager" },
  { value: "finance_manager", label: "Finance Manager" },

  // Healthcare
  { value: "general_physician", label: "General Physician" },
  { value: "surgeon", label: "Surgeon" },
  { value: "dentist", label: "Dentist" },
  { value: "pediatrician", label: "Pediatrician" },
  { value: "cardiologist", label: "Cardiologist" },
  { value: "neurologist", label: "Neurologist" },
  { value: "psychiatrist", label: "Psychiatrist" },
  { value: "gynecologist", label: "Gynecologist" },
  { value: "radiologist", label: "Radiologist" },
  { value: "pharmacist", label: "Pharmacist" },
  { value: "nurse", label: "Nurse" },
  { value: "medical_technician", label: "Medical Technician" },

  // Legal
  { value: "lawyer", label: "Lawyer" },
  { value: "legal_advisor", label: "Legal Advisor" },
  { value: "paralegal", label: "Paralegal" },
  { value: "judge", label: "Judge" },
  { value: "corporate_lawyer", label: "Corporate Lawyer" },
  { value: "criminal_lawyer", label: "Criminal Lawyer" },

  // Creative and Media
  { value: "content_writer", label: "Content Writer" },
  { value: "copywriter", label: "Copywriter" },
  { value: "video_editor", label: "Video Editor" },
  { value: "photographer", label: "Photographer" },
  { value: "social_media_manager", label: "Social Media Manager" },

  // Education
  { value: "teacher", label: "Teacher" },
  { value: "professor", label: "Professor" },
  { value: "academic_counselor", label: "Academic Counselor" },
  { value: "principal", label: "Principal" },

  // Other Fields
  { value: "customer_support", label: "Customer Support" },
  { value: "chef", label: "Chef" },
  { value: "mechanical_engineer", label: "Mechanical Engineer" },
  { value: "civil_engineer", label: "Civil Engineer" },
  { value: "electrician", label: "Electrician" },
  { value: "plumber", label: "Plumber" },
  { value: "architect", label: "Architect" },
  { value: "pilot", label: "Pilot" },
  { value: "flight_attendant", label: "Flight Attendant" },

  // Internships and Entry Level
  { value: "intern", label: "Intern" },
  { value: "trainee", label: "Trainee" },
];

export const genderOption = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
];

export const bangladeshDistricts = [
  { value: "bagerhat", label: "Bagerhat" },
  { value: "bandarban", label: "Bandarban" },
  { value: "barguna", label: "Barguna" },
  { value: "barisal", label: "Barisal" },
  { value: "bhola", label: "Bhola" },
  { value: "bogra", label: "Bogra" },
  { value: "brahmanbaria", label: "Brahmanbaria" },
  { value: "chandpur", label: "Chandpur" },
  { value: "chittagong", label: "Chittagong" },
  { value: "chuadanga", label: "Chuadanga" },
  { value: "comilla", label: "Comilla" },
  { value: "coxsbazar", label: "Cox's Bazar" },
  { value: "dhaka", label: "Dhaka" },
  { value: "dinajpur", label: "Dinajpur" },
  { value: "faridpur", label: "Faridpur" },
  { value: "feni", label: "Feni" },
  { value: "gaibandha", label: "Gaibandha" },
  { value: "gazipur", label: "Gazipur" },
  { value: "gopalganj", label: "Gopalganj" },
  { value: "habiganj", label: "Habiganj" },
  { value: "jamalpur", label: "Jamalpur" },
  { value: "jessore", label: "Jessore" },
  { value: "jhenaidah", label: "Jhenaidah" },
  { value: "joypurhat", label: "Joypurhat" },
  { value: "khagrachari", label: "Khagrachari" },
  { value: "khulna", label: "Khulna" },
  { value: "kishoreganj", label: "Kishoreganj" },
  { value: "kurigram", label: "Kurigram" },
  { value: "kushtia", label: "Kushtia" },
  { value: "lakshmipur", label: "Lakshmipur" },
  { value: "lalmonirhat", label: "Lalmonirhat" },
  { value: "madaripur", label: "Madaripur" },
  { value: "magura", label: "Magura" },
  { value: "manikganj", label: "Manikganj" },
  { value: "meherpur", label: "Meherpur" },
  { value: "moulvibazar", label: "Moulvibazar" },
  { value: "munshiganj", label: "Munshiganj" },
  { value: "mymensingh", label: "Mymensingh" },
  { value: "naogaon", label: "Naogaon" },
  { value: "narail", label: "Narail" },
  { value: "narayanganj", label: "Narayanganj" },
  { value: "narsingdi", label: "Narsingdi" },
  { value: "natore", label: "Natore" },
  { value: "netrokona", label: "Netrokona" },
  { value: "nilphamari", label: "Nilphamari" },
  { value: "noakhali", label: "Noakhali" },
  { value: "pabna", label: "Pabna" },
  { value: "panchagarh", label: "Panchagarh" },
  { value: "patuakhali", label: "Patuakhali" },
  { value: "pirojpur", label: "Pirojpur" },
  { value: "rajbari", label: "Rajbari" },
  { value: "rajshahi", label: "Rajshahi" },
  { value: "rangamati", label: "Rangamati" },
  { value: "rangpur", label: "Rangpur" },
  { value: "satkhira", label: "Satkhira" },
  { value: "shariatpur", label: "Shariatpur" },
  { value: "sherpur", label: "Sherpur" },
  { value: "sirajganj", label: "Sirajganj" },
  { value: "sunamganj", label: "Sunamganj" },
  { value: "sylhet", label: "Sylhet" },
  { value: "tangail", label: "Tangail" },
  { value: "thakurgaon", label: "Thakurgaon" },
];

export const upazilas = [
  // Dhaka District
  { value: "dhamrai", label: "Dhamrai" },
  { value: "keraniganj", label: "Keraniganj" },
  { value: "nawabganj", label: "Nawabganj" },
  { value: "savar", label: "Savar" },

  // Rangpur District
  { value: "badarganj", label: "Badarganj" },
  { value: "gangachara", label: "Gangachara" },
  { value: "kaunia", label: "Kaunia" },
  { value: "mithapukur", label: "Mithapukur" },
  { value: "pirgacha", label: "Pirgacha" },
  { value: "pirganj", label: "Pirganj" },
  { value: "rangpur_sadar", label: "Rangpur Sadar" },
  { value: "taraganj", label: "Taraganj" },

  // Rajshahi District
  { value: "bagha", label: "Bagha" },
  { value: "bagmara", label: "Bagmara" },
  { value: "charghat", label: "Charghat" },
  { value: "durgapur", label: "Durgapur" },
  { value: "godagari", label: "Godagari" },
  { value: "mohanpur", label: "Mohanpur" },
  { value: "paba", label: "Paba" },
  { value: "puthia", label: "Puthia" },
  { value: "tanore", label: "Tanore" },

  // Mymensingh District
  { value: "bhaluka", label: "Bhaluka" },
  { value: "dhobaura", label: "Dhobaura" },
  { value: "fulbaria", label: "Fulbaria" },
  { value: "gaffargaon", label: "Gaffargaon" },
  { value: "gouripur", label: "Gouripur" },
  { value: "haluaghat", label: "Haluaghat" },
  { value: "ishwarganj", label: "Ishwarganj" },
  { value: "mymensingh_sadar", label: "Mymensingh Sadar" },
  { value: "nakla", label: "Nakla" },
  { value: "nalitabari", label: "Nalitabari" },
  { value: "phulpur", label: "Phulpur" },
  { value: "tarakanda", label: "Tarakanda" },

  // Sylhet District
  { value: "balaganj", label: "Balaganj" },
  { value: "beanibazar", label: "Beanibazar" },
  { value: "bishwanath", label: "Bishwanath" },
  { value: "companiganj", label: "Companiganj" },
  { value: "dakshin_surma", label: "Dakshin Surma" },
  { value: "fenchuganj", label: "Fenchuganj" },
  { value: "golapganj", label: "Golapganj" },
  { value: "gowainghat", label: "Gowainghat" },
  { value: "kanaighat", label: "Kanaighat" },
  { value: "sylhet_sadar", label: "Sylhet Sadar" },
  { value: "zakiganj", label: "Zakiganj" },

  // Khulna District
  { value: "batiaghata", label: "Batiaghata" },
  { value: "daulatpur", label: "Daulatpur" },
  { value: "dighalia", label: "Dighalia" },
  { value: "dumuria", label: "Dumuria" },
  { value: "khalishpur", label: "Khalishpur" },
  { value: "khulna_sadar", label: "Khulna Sadar" },
  { value: "koira", label: "Koira" },
  { value: "phultala", label: "Phultala" },
  { value: "rupsha", label: "Rupsha" },
  { value: "terokhada", label: "Terokhada" },

  // Cumilla District
  { value: "brahmanpara", label: "Brahmanpara" },
  { value: "burichang", label: "Burichang" },
  { value: "chandina", label: "Chandina" },
  { value: "chauddagram", label: "Chauddagram" },
  { value: "daudkandi", label: "Daudkandi" },
  { value: "debidwar", label: "Debidwar" },
  { value: "homna", label: "Homna" },
  { value: "laksham", label: "Laksham" },
  { value: "muradnagar", label: "Muradnagar" },
  { value: "nandail", label: "Nandail" },
  { value: "titas", label: "Titas" },

  // Barishal District
  { value: "agailjhara", label: "Agailjhara" },
  { value: "babuganj", label: "Babuganj" },
  { value: "banaripara", label: "Banaripara" },
  { value: "gaurnadi", label: "Gaurnadi" },
  { value: "hizla", label: "Hizla" },
  { value: "mehendiganj", label: "Mehendiganj" },
  { value: "muladi", label: "Muladi" },
  { value: "barisal_sadar", label: "Barishal Sadar" },

  // Chattogram District
  { value: "anwara", label: "Anwara" },
  { value: "banshkhali", label: "Banshkhali" },
  { value: "boalkhali", label: "Boalkhali" },
  { value: "chandanaish", label: "Chandanaish" },
  { value: "fatikchhari", label: "Fatikchhari" },
  { value: "hathazari", label: "Hathazari" },
  { value: "lohagara", label: "Lohagara" },
  { value: "mirsharai", label: "Mirsharai" },
  { value: "patiya", label: "Patiya" },
  { value: "rangunia", label: "Rangunia" },
  { value: "raoza", label: "Raozan" },
  { value: "sandwip", label: "Sandwip" },
  { value: "satkania", label: "Satkania" },
  { value: "sitakunda", label: "Sitakunda" },
];
